from enum import IntEnum


class FeedType(IntEnum):
    SUBSCRIBE_FULL_5_DEPTH = 21
    UNSUBSCRIBE_FULL_5_DEPTH = 22

    SUBSCRIBE_FULL_MARKET_20_DEPTH = 23
    UNSUBSCRIBE_FULL_MARKET_20_DEPTH = 24

    SUBSCRIBE_FULL_MARKET_200_DEPTH = 23
    UNSUBSCRIBE_FULL_MARKET_200_DEPTH = 24
