from enum import IntEnum


class RequestCode(IntEnum):
    CONNECT_FEED = 11
    DISCONNECT_FEED = 12

    SUBSCRIBE_TICKER = 15
    UNSUBSCRIBE_TICKER = 16

    SUBSCRIBE_QUOTE = 17
    UNSUBSCRIBE_QUOTE = 18

    SUBSCRIBE_FULL = 21
    UNSUBSCRIBE_FULL = 22

    SUBSCRIBE_FULL_MARKET_DEPTH = 23
    UNSUBSCRIBE_FULL_MARKET_DEPTH = 24